version: "3.8"
services:
  sqlite:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./api/.db/:/root/db/


  api:
    image: "food-api"
    build:
      context: api
      dockerfile: "Dockerfile"
      target: "dev"
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
