version: "3.8"
services:
  postgres:
    image: "postgres:13.7"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=food-db"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - ./db_fixtures/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db_fixtures:/tmp/pg-fixtures/


#  api:
#    image: "food-api"
#    build:
#      context: api
#      dockerfile: "Dockerfile"
#      target: "dev"
#    tty: true
#    stdin_open: true
#    ports:
#      - "3000:3000"
