const MAX_PREVIEW_CARD_TEXT_LENGTH = 200;
const TOAST_IMPORTANT_TIME_OUT_MS = 4000;
const TOAST_TIME_OUT_MS = 1500;
const DEFAULT_SKIP = 0;
const DEFAULT_LIMIT = 12;

export { MAX_PREVIEW_CARD_TEXT_LENGTH, TOAST_IMPORTANT_TIME_OUT_MS, TOAST_TIME_OUT_MS, DEFAULT_SKIP, DEFAULT_LIMIT };
